# Generated by Django 2.0.6 on 2018-06-30 10:34

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20180630_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='课程详情'),
        ),
    ]
